export const INTERESTS = [
  "Technology",
  "Education",
  "Marketing",
  "Finance",
  "Health",
  "Retail",
  "Consulting",
  "Creative",
  "Food & Beverage",
  "Real Estate",
  "E-commerce",
  "Fitness & Wellness",
  "Travel & Tourism",
  "Fashion & Apparel",
  "Media & Entertainment",
  "Agriculture",
  "Manufacturing",
  "Logistics & Supply Chain",
  "Legal & Compliance",
  "Human Resources",
  "Data & Analytics",
  "Software & Apps",
  "Social Impact",
  "Environment & Sustainability"
];
