export const PLACEHOLDERS = {
  firstName: "Abebe",
  lastName: "Kebede",
  fullName: "Abebe Kebede",
  email: "abebe@gmail.com",
  password: "Enter your password",
  passwordNew: "At least 8 characters",
  passwordConfirm: "Re-enter your password",
  phone: "0911 234 567",
  company: "Selam Trading PLC",
  addressLine1: "Bole Road, near Edna Mall",
  addressLine2: "Kirkos Sub-city",
  city: "Addis Ababa",
  region: "Addis Ababa",
  country: "Ethiopia",
  taxId: "TIN (optional)",
  profession: "Accountant, teacher, shop owner…",
  employer: "Ethiopian Airlines, bank, or self-employed",
  monthlySalary: "e.g. 25,000 ETB",
  availableCapital: "e.g. 100,000 ETB",
  hoursPerWeek: "e.g. 15 hours",
  maxCapital: "e.g. 500,000 ETB",
  searchSkills: "Search skills…",
  searchInterests: "Search sectors…",
  searchPlans: "Search plans…",
  searchIdeas: "Search ideas…",
  searchUsers: "Search users…",
  searchByName: "Search by name or category…",
  searchCategory: "e.g. Agriculture, retail…",
  contactName: "Abebe Kebede",
  contactSubject: "Question about my plan",
  contactMessage: "How can we help you?",
  businessIdea: "e.g. Coffee shop in Bole, Addis Ababa",
  tagSearch: "Search to add…"
};

export const BILLING_PLACEHOLDERS = {
  fullName: PLACEHOLDERS.fullName,
  company: PLACEHOLDERS.company,
  phone: PLACEHOLDERS.phone,
  addressLine1: PLACEHOLDERS.addressLine1,
  addressLine2: PLACEHOLDERS.addressLine2,
  city: PLACEHOLDERS.city,
  region: PLACEHOLDERS.region,
  country: PLACEHOLDERS.country,
  taxId: PLACEHOLDERS.taxId
};
