export const SKILLS = [
  "Excel",
  "Power BI",
  "SQL",
  "Data Analysis",
  "Python",
  "JavaScript",
  "Programming",
  "Project Management",
  "Communication",
  "Teaching",
  "Coaching",
  "SEO",
  "Social Media",
  "Copywriting",
  "Ads Management",
  "Content Creation",
  "Video Editing",
  "Graphic Design",
  "Adobe Suite",
  "UI/UX",
  "Branding",
  "Financial Planning",
  "Accounting",
  "Legal Knowledge",
  "HR Management",
  "Networking",
  "Sales",
  "Customer Service",
  "Logistics",
  "Negotiation",
  "Marketing",
  "IT Support",
  "Networking",
  "Cybersecurity",
  "Cloud Services",
  "Cooking",
  "Food Safety",
  "Fitness Training",
  "Nutrition",
  "Photography",
  "Storytelling",
  "Research",
  "Documentation",
  "Creativity",
  "Leadership"
];
